import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/layout'
// Analytics tracking 



// Initialize google analytics page view tracking

export default function Home() {

  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<Layout>
  
</Layout>

    </div>
  )
}
