version: '3.8'
services: 

    backend:
        build:
            context: .
            dockerfile: React.Dockerfile
        ports: 
            - 8000:8000
        volumes: 
            - build:/app
        
        
    nginx:
        image: nginx:latest
        ports: 
            - 80:80
        expose:
            - "80"
        volumes: 
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
            - build:/var/www/app
volumes:  
    build: